name: Deploy to Cloud Run

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud (pin project)
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Debug: show who/where
        run: gcloud auth list && gcloud config list

      - name: Enable required APIs (idempotent)
        run: gcloud services enable run.googleapis.com cloudbuild.googleapis.com artifactregistry.googleapis.com secretmanager.googleapis.com generativelanguage.googleapis.com --project "${{ secrets.GCP_PROJECT }}"

      - name: Deploy to Cloud Run from source
        run: gcloud run deploy "${{ secrets.SERVICE_NAME }}" --project "${{ secrets.GCP_PROJECT }}" --region "${{ secrets.RUN_REGION }}" --source . --allow-unauthenticated --set-env-vars SHOW_DIAGNOSTICS=false --set-secrets GOOGLE_API_KEY=google_api_key:latest

